# Simplified Python NumPy Tutorial –Learn NumPy Arrays_ 2021

*prepared by_Nelson_Otuma_Ongaya

**What are NumPy Arrays?**
+ NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.

*The very first reason to choose python NumPy array is that it occupies less memory as compared to list. Then, it is pretty fast in terms of execution and at the same time, it is very convenient to work with NumPy. So these are the major advantages that Python NumPy array has over list. Don’t worry, I am going to prove the above points one by one practically on Jupyter notebook.

*Lets get started...;

In [1]:
# Import Numpy Library
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

### Numpy Array Creation

In [2]:

list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
#we display the type of an object
type(list1)


list

In [4]:
#we can now convert list to Numpy Array
arr1 = np.array(list1)
arr1


array([10, 20, 30, 40, 50, 60])

In [5]:
#Memory address of an array object
arr1.data

In [6]:
# Display type of an object
type(arr1)

numpy.ndarray

In [7]:
#Datatype of array
arr1.dtype

dtype('int32')

In [8]:
# convert Integer Array to float
arr1.astype(float)


array([10., 20., 30., 40., 50., 60.])

In [9]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [12]:
#Shape of Array
arr3 = np.arange(0,10)
arr3.shape


(10,)

In [13]:
arr3


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Size of array
arr3.size

10

In [15]:
# Dimension 
arr3.ndim

1

In [16]:
# Datatype of object
arr3.dtype

dtype('int32')

In [17]:
# Bytes consumed by one element of an array object
arr3.itemsize


4

In [18]:
# Bytes consumed by an array object
arr3.nbytes


40

In [19]:
# Length of array
len(arr3)

10

In [20]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
# Generate an array of ones with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# Repeat 10 five times in an array
np.repeat(10,5)


array([10, 10, 10, 10, 10])

In [23]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [24]:
# Array of 10's
np.full(5,10)


array([10, 10, 10, 10, 10])

In [25]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 ==1]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2 == 0]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [28]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [29]:
# Create an array of random values
np.random.random(4)

array([0.51581103, 0.64883352, 0.82381854, 0.41484308])

In [30]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,5)
    

array([193,  51, 448, 182,  16])

In [31]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,10)


array([400, 326, 467,  63, 110, 155,  70, 157, 103,  18])

In [32]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [33]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)


array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [34]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [35]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1    

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [37]:
# Extract Integer part
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [38]:
# Truncate decimal part
np.trunc(f1)


array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [39]:
# Convert Float Array to Integer array
f1.astype(int)


array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [40]:
# Normal distribution (mean=0 and variance=1)
b2 =np.random.randn(10)
b2


array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [41]:
arr1


array([10, 20, 30, 40, 50, 60])

In [42]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
 print(index, value)


(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


**Operations on an Array**


In [43]:
arr2 = np.arange(1,20)
arr2


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
# Sum of all elements in an array
arr2.sum()


190

In [45]:
# Cumulative Sum
np.cumsum(arr2)


array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [46]:
# Find Minimum number in an array
arr2.min()


1

In [47]:
# Find MAX number in an array
arr2.max()


19

In [48]:
# Find INDEX of Minimum number in an array
arr2.argmin()


0

In [49]:
# Find INDEX of MAX number in an array
arr2.argmax()

18

In [50]:
# Find mean of all numbers in an array
arr2.mean()


10.0

In [51]:
# Find median of all numbers present in arr2
np.median(arr2)


10.0

In [52]:
# Variance
np.var(arr2)


30.0

In [53]:
# Standard deviation
np.std(arr2)

5.477225575051661

In [54]:
# Calculating percentiles
np.percentile(arr2,70)

13.6

In [55]:
# 10th & 70th percentile
np.percentile(arr2,[10,70])


array([ 2.8, 13.6])

**Operations on a 2D Array**

In [56]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [57]:
# SUM of all numbers in a 2D array
A.sum()


129

In [58]:
# MAX number in a 2D array
A.max()

22

In [59]:
# Minimum
A.min()


0

In [60]:
# Column wise mimimum value 
np.amin(A, axis=0)


array([1, 2, 1, 0])

In [61]:
# Row wise mimimum value 
np.amin(A, axis=1)


array([0, 5, 1, 3])

In [62]:
# Mean of all numbers in a 2D array
A.mean()


8.0625

In [63]:
# Mean
np.mean(A)

8.0625

In [64]:
# Median
np.median(A)


6.5

In [65]:
# 50 percentile = Median
np.percentile(A,50)


6.5

In [66]:
np.var(A)


40.30859375

In [67]:
np.std(A)


6.348904925260734

In [68]:
np.percentile(arr2,70)

13.6

In [69]:
# Enumerate for Numpy 2D Arrays
for index, value in np.ndenumerate(A):
 print(index, value)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


**Reading elements of an array**


In [70]:
a = np.array([7,5,3,9,0,2])


In [71]:
# Access first element of the array
a[0]


7

In [72]:
# Access all elements of Array except first one.
a[1:]

array([5, 3, 9, 0, 2])

In [73]:
# Fetch 2nd , 3rd & 4th value from the Array
a[1:4]

array([5, 3, 9])

In [74]:
# Get last element of the array
a[-1]


2

In [75]:
a[-3]

9

In [76]:
a[-6]


7

In [77]:
a[-3:-1]

array([9, 0])

**Replace elements in array**

In [78]:
ar = np.arange(1,20)
ar


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [79]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar % 2 == 0, 0 , ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [80]:
ar2 = np.array([10, 20 , 30 , 10 ,10 ,20, 20])
ar2


array([10, 20, 30, 10, 10, 20, 20])

In [81]:
# Replace 10 with value 99
rep2 = np.where(ar2 == 10, 99 , ar2)
print(rep2)


[99 20 30 99 99 20 20]


In [82]:
p2 = np.arange(0,100,10)
p2


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
# Replace values at INDEX loc 0,3,5 with 33,55,99
np.put(p2, [0, 3 , 5], [33, 55, 99])
p2


array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

**Missing Values in an array**

In [84]:
a = np.array([10 ,np.nan,20,30,60,np.nan,90,np.inf])
a


array([10., nan, 20., 30., 60., nan, 90., inf])

In [85]:
# Search for missing values and return as a boolean array
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [86]:
# Index of missing values in an array
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [87]:
# Replace all missing values with 99
a[np.isnan(a)] = 99
a


array([10., 99., 20., 30., 60., 99., 90., inf])

In [88]:
# Check if array has any NULL value
np.isnan(a).any()


False

**Stack Arrays Vertically**

In [89]:
a = np.zeros(20).reshape(2,-1)
b = np.repeat(1, 20).reshape(2,-1)
a


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [91]:
np.vstack([a,b])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [92]:
a1 = np.array([[1], [2], [3]])
b1 = np.array([[4], [5], [6]])


In [93]:
a1

array([[1],
       [2],
       [3]])

In [94]:
b1

array([[4],
       [5],
       [6]])

In [95]:
np.vstack([a1,b1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**Stack Arrays Horizontally**

In [96]:
np.hstack([a,b])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [97]:
np.hstack([a1,b1])

array([[1, 4],
       [2, 5],
       [3, 6]])

**Common items between two Arrays**

In [98]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [99]:
np.intersect1d(c1,c2)

array([20, 40, 60])

**Remove Common Elements**

In [100]:
# Remove common elements of C1 & C2 array from C1
np.setdiff1d(c1,c2)

array([10, 30, 50])

**Process Elements on Conditions**

In [101]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])
np.where(a == b) # returns the indices of elements in an input array where the g

(array([1, 4], dtype=int64),)

In [102]:
# Return an array where condition is satisfied
a[np.where(a == b)]


array([2, 8])

In [103]:
# Return all numbers betweeen 20 & 35
a1 = np.arange(0,60)
a1[np.where ((a1>20) & (a1<35))]


array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [104]:
# Return all numbers betweeen 20 & 35 OR numbers divisible by 10
a1 = np.arange(0,60)
a1[np.where (((a1>20) & (a1<35)) | (a1 % 10 ==0)) ]


array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [105]:
# Return all numbers betweeen 20 & 35 using np.logical_and
a1[np.where(np.logical_and(a1>20, a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

**Check for elements in an Array using
isin()**

In [106]:
a = np.array([10,20,30,40,50,60,70])
a


array([10, 20, 30, 40, 50, 60, 70])

In [107]:
# Check whether number 11 & 20 are present in an array
np.isin(a, [11,20])


array([False,  True, False, False, False, False, False])

In [108]:
#Display the matching numbers
a[np.isin(a,20)]

array([20])

In [109]:
# Check whether number 33 is present in an array
np.isin(a, 33)


array([False, False, False, False, False, False, False])

In [110]:
a[np.isin(a, 33)]
    

array([], dtype=int32)

In [111]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b

array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [112]:
# Check whether number 10 & 70 are present in an array
np.isin(b, [10,70])


array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [113]:
# Display the indices where match occurred
np.where(np.isin(b, [10,70]))


(array([0, 4, 5, 6, 8], dtype=int64),)

In [114]:
# Display the matching values
b[np.where(np.isin(b, [10,70]))]


array([10, 10, 10, 70, 70])

In [115]:
# Display the matching values
b[np.isin(b, [10,70])]


array([10, 10, 10, 70, 70])

**Reverse Array**

In [116]:
a4 = np.arange(10,30)


In [117]:
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [118]:
# Reverse the array
a4[::-1]


array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [119]:
# Reverse the array
np.flip(a4)


array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [120]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a3


array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [121]:
# Reverse ROW positions
a3[::-1,]


array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [122]:
# Reverse COLUMN positions
a3[:,::-1]


array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [123]:
# Reverse both ROW & COLUMN positions
a3[::-1,::-1]


array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

**Sorting Array**

In [124]:
a = np.array([10,5,2,22,12,92,17,33])

In [125]:
# Sort array in ascending order
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [126]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [127]:
# Sort along rows
np.sort(a3)


array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [128]:
# Sort along rows
np.sort(a3,axis =1)


array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [129]:
# Sort along columns
np.sort(a3,axis =0)


array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [130]:
# Sort in descending order
b = np.sort(a)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [131]:
# Sort in descending order
c = np.sort(a)
np.flip(c)


array([92, 33, 22, 17, 12, 10,  5,  2])

In [132]:
# Sort in descending order
a[::-1].sort()
a

array([92, 33, 22, 17, 12, 10,  5,  2])

**"N" Largest & Smallest Numbers in an
Array**

In [133]:
p = np.arange(0,50)
p


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [134]:
np.random.shuffle(p)
p

array([27, 26, 35, 41, 45, 43,  6,  4, 34, 16,  3,  1, 31, 25, 48, 40, 21,
        2, 13, 47,  5, 37, 14, 23, 32, 22,  8, 20, 44, 28, 36, 10, 30, 19,
       24, 29, 33, 42, 11, 17, 12,  0, 15, 49,  7, 18,  9, 46, 38, 39])

In [135]:
# Return "n" largest numbers in an Array
#p[np.argpartition(-p,n)[:n]]

In [136]:
# Return "n" smallest numbers in an Array
#p[np.argsort(-p)[-n:]]


In [137]:
# Return "n" smallest numbers in an Array
#p[np.argpartition(p,n)[:n]]

**Repeating Sequences**

In [138]:
a5 = [10,20,30] 
a5

[10, 20, 30]

In [139]:
# Repeat whole array twice
np.tile(a5, 2)

array([10, 20, 30, 10, 20, 30])

In [140]:
# Repeat each element in an array thrice
np.repeat(a5, 3)


array([10, 10, 10, 20, 20, 20, 30, 30, 30])

**Compare Arrays**

In [141]:
d1 = np.arange(0,10)
d1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
d2 = np.arange(0,10)
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
d3 = np.arange(10,20)
d3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [144]:
d4 = d1[::-1]
d4

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [145]:
# Compare arrays using "allclose" function. If this function returns True then A
res1 = np.allclose(d1,d2)
res1

True

In [146]:
# Compare arrays using "allclose" function. If this function returns False then 
res2 = np.allclose(d1,d3)
res2


False

In [147]:
# Compare arrays using "allclose" function.
res3 = np.allclose(d1,d4)
res3

False

**Frequent Values in an Array**

In [148]:
# unique numbers in an array
b = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10])
np.unique(b)


array([10, 20, 30])

In [149]:
# unique numbers in an array along with the count E.g value 10 occurred maximum 
val , count = np.unique(b,return_counts=True)
val,count



(array([10, 20, 30]), array([6, 3, 4], dtype=int64))

In [150]:
# 10 is the most frequent value 
np.bincount(b).argmax()


10

**Read-Only Array**

In [151]:
d5 = np.arange(10,100,10)
d5


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [152]:
# Make arrays immutable 
d5.flags.writeable = False

In [153]:
#d5[0] = 80

**Printing Options**

In [154]:
# Display values upto 4 decimal place
np.set_printoptions(precision=4)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.6544, 90.7864])

In [155]:
# Display values upto 2 decimal place
np.set_printoptions(precision=2)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.65, 90.79])

In [156]:
# Array Summarization
np.set_printoptions(threshold=3)
np.arange(200)


array([  0,   1,   2, ..., 197, 198, 199])

In [157]:
# Reset Formatter
np.set_printoptions(precision=8,suppress=False, threshold=1000, formatter=None)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.65439876, 90.78640984])

In [158]:
np.arange(1,1100)


array([   1,    2,    3, ..., 1097, 1098, 1099])

In [159]:
# Display all values
np.set_printoptions(threshold=np.inf)
np.arange(1,1100)


array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

**Vector Addition**

In [160]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1+v2
v3 = np.add(v1,v2)
print('V3 =' ,v3)

V3 = [4 6]


 **Multiplication of vectors **  

In [161]:
a1 = [5 , 6 ,8]
a2 = [4, 7 , 9]
print(np.multiply(a1,a2))


[20 42 72]


**Dot Product**

In [162]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
dotp = a1@a2
print(" Dot product - ",dotp)
dotp = np.dot(a1,a2)
print(" Dot product usign np.dot",dotp)
dotp = np.inner(a1,a2)
print(" Dot product usign np.inner", dotp)
dotp = sum(np.multiply(a1,a2))
print(" Dot product usign np.multiply & sum",dotp)
dotp = np.matmul(a1,a2)
print(" Dot product usign np.matmul",dotp)
dotp = 0
for i in range(len(a1)):
 dotp = dotp + a1[i]*a2[i]
print(" Dot product usign for loop" , dotp)


 Dot product -  32
 Dot product usign np.dot 32
 Dot product usign np.inner 32
 Dot product usign np.multiply & sum 32
 Dot product usign np.matmul 32
 Dot product usign for loop 32


**Length of Vector**

In [163]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length


9.539392014169456

In [164]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(sum(np.multiply(v3,v3)))
length

9.539392014169456

In [165]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.matmul(v3,v3))
length


9.539392014169456

**Normalized Vector**

In [166]:
#First Method
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1 = v1/length_v1
length_v1 , norm_v1


(3.605551275463989, array([0.5547002 , 0.83205029]))

In [167]:
#Second Method
v1 = [2,3]
norm_v1 = v1/np.linalg.norm(v1)
norm_v1


array([0.5547002 , 0.83205029])

**Angle between vectors**

In [168]:
#First Method
v1 = np.array([4,3])
v2 = np.array([-3,4])
lengthV1 = np.sqrt(np.dot(v1,v1)) 
lengthV2 = np.sqrt(np.dot(v2,v2))
ang = np.rad2deg(np.arccos( np.dot(v1,v2) / (lengthV1 * lengthV2)))
print('Angle between Vectors - %s' %ang)


Angle between Vectors - 90.0


**Inner & outer products**

In [169]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.inner(v1,v2)
print("\n Inner Product ==> \n", np.inner(v1,v2))
print("\n Outer Product ==> \n", np.outer(v1,v2))



 Inner Product ==> 
 32

 Outer Product ==> 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Vector Cross Product**

In [170]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("\nVector Cross Product ==> \n", np.cross(v1,v2))


Vector Cross Product ==> 
 [-3  6 -3]


**Matrix Creation**

In [171]:
# Create a 4x4 matrix
A = np.array([[1,2,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [172]:
# Datatype of Matrix
A.dtype

dtype('int32')

In [173]:
B = np.array([[1.5,2.07,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
B


array([[ 1.5 ,  2.07,  3.  ,  4.  ],
       [ 5.  ,  6.  ,  7.  ,  8.  ],
       [10.  , 11.  , 12.  , 13.  ],
       [14.  , 15.  , 16.  , 17.  ]])

In [174]:
# Datatype of Matrix
B.dtype


dtype('float64')

In [175]:
# Shape of Matrix
A.shape


(4, 4)

In [176]:
# Generate a 4x4 zero matrix
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [177]:
#Shape of Matrix
z1 = np.zeros((4,4))
z1.shape


(4, 4)

In [178]:
# Generate a 5x5 matrix filled with ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [179]:
# Return 10x10 matrix of random integer numbers between 0 to 500
np.random.randint(0,500, (10,10))

array([[435, 262, 472, 103, 229, 366,  71, 357, 452, 244],
       [407, 163, 207, 226, 451, 338, 441, 461,  46, 131],
       [ 46, 485, 285, 470, 149, 378,  21, 465,  23, 235],
       [254, 383,  94, 356, 199, 276,  27, 459,   5, 305],
       [470, 217, 191,  82,  77, 358, 131, 184, 383, 142],
       [383,  49, 343,  52, 253, 397, 431, 433, 280, 404],
       [448, 180, 316, 303, 370, 285, 316, 309, 395,  40],
       [219, 301,  97, 408, 292, 166, 137, 125,  52,  67],
       [299, 129,  79,  68, 196, 484,  61, 146, 307, 270],
       [412, 401,  87,  46,  52, 144, 454, 455,  84,  10]])

In [180]:
arr2


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [181]:
mat1 = np.random.randint(0,1000,100).reshape(10,10)
mat1

array([[190, 874,  96, 122, 235, 487, 697, 663, 470, 469],
       [ 26,  76, 578, 232, 566, 657, 705, 697, 985, 770],
       [592,  50, 834,  88, 591, 505, 861, 518, 348, 554],
       [ 22, 377, 244, 880, 916, 921, 895,  97, 110, 950],
       [ 71, 507, 968, 208, 733, 192, 876, 575, 488, 359],
       [208, 422, 813, 359, 615, 884, 163, 537, 223,  75],
       [456,  11, 844, 207, 369, 891, 818, 751, 662, 101],
       [571, 834, 358, 490, 634,   1, 546, 549, 441,  35],
       [810, 115, 869, 684, 242, 108, 177, 671,  79,  85],
       [515, 311, 841, 221, 478, 611,  40, 694, 984, 350]])

In [182]:
mat1[0,0]

190

In [183]:
mat1[mat1 > 500]


array([874, 697, 663, 578, 566, 657, 705, 697, 985, 770, 592, 834, 591,
       505, 861, 518, 554, 880, 916, 921, 895, 950, 507, 968, 733, 876,
       575, 813, 615, 884, 537, 844, 891, 818, 751, 662, 571, 834, 634,
       546, 549, 810, 869, 684, 671, 515, 841, 611, 694, 984])

In [184]:
# Identity Matrix : https://en.wikipedia.org/wiki/Identity_matrix
I = np.eye(9)
I


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [185]:
# Diagonal Matrix : https://en.wikipedia.org/wiki/Diagonal_matrix
D = np.diag([1,2,3,4,5,6,7,8])
D


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [186]:
# Traingular Matrices (lower & Upper triangular matrix) : https://en.wikipedia.o
M = np.random.randn(5,5)
U = np.triu(M)
L = np.tril(M)
print("lower triangular matrix - \n" , M)
print("\n")
print("lower triangular matrix - \n" , L)
print("\n")
print("Upper triangular matrix - \n" , U)


lower triangular matrix - 
 [[ 0.30563151  0.24317761  0.86416488 -1.56093145 -0.25189695]
 [-0.57812026  0.23699563  0.20078047  0.32784474  0.67448519]
 [-0.17405654  0.78013972 -0.38325813 -0.40931848  0.34353919]
 [ 0.19627532 -0.982776    2.23155524 -0.97139257 -1.52233287]
 [ 1.13370299  0.52818673  0.39346076 -0.63050663 -1.39828968]]


lower triangular matrix - 
 [[ 0.30563151  0.          0.          0.          0.        ]
 [-0.57812026  0.23699563  0.          0.          0.        ]
 [-0.17405654  0.78013972 -0.38325813  0.          0.        ]
 [ 0.19627532 -0.982776    2.23155524 -0.97139257  0.        ]
 [ 1.13370299  0.52818673  0.39346076 -0.63050663 -1.39828968]]


Upper triangular matrix - 
 [[ 0.30563151  0.24317761  0.86416488 -1.56093145 -0.25189695]
 [ 0.          0.23699563  0.20078047  0.32784474  0.67448519]
 [ 0.          0.         -0.38325813 -0.40931848  0.34353919]
 [ 0.          0.          0.         -0.97139257 -1.52233287]
 [ 0.          0.          0

In [187]:
# Generate a 5X5 matrix with a given fill value of 8
np.full((5,5) , 8)


array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [188]:
# Generate 5X5 matrix of Random float numbers between 10 to 20
np.random.uniform(10,20, size=(5,5))

array([[16.31128977, 10.17791258, 18.38550666, 15.25546014, 13.70937906],
       [14.25749526, 12.65095349, 14.46407618, 19.82653236, 17.5205419 ],
       [15.20926194, 14.62382566, 10.67456703, 16.22839782, 17.19619446],
       [14.50735946, 16.84777378, 17.32571431, 11.49804788, 16.0899551 ],
       [18.62653884, 10.1162064 , 17.99914635, 19.53490348, 11.05180232]])

In [189]:
A


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [190]:
# Collapse Matrix into one dimension array
A.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

In [191]:
# Collapse Matrix into one dimension array
A.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

**Reading elements of a Matrix**

In [192]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [193]:
# Fetch first row of matrix
A[0,]

array([1, 2, 3, 4])

In [194]:
# Fetch first column of matrix
A[:,0]

array([ 1,  5, 10, 14])

In [195]:
# Fetch first element of the matrix
A[0,0]

1

In [196]:
A[1:3 , 1:3]

array([[ 6,  7],
       [11, 12]])

**Reverse Rows / Columns of a Matrix**

In [197]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [198]:
# Reverse rows
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [199]:
#Reverse Columns
arr[:, ::-1]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

**SWAP Rows & Columns**

In [200]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [201]:
# swap rows 0 & 1
m1[[0,1]] = m1[[1,0]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [202]:
# swap rows 2 & 3
m1[[3,2]] = m1[[2,3]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [203]:
m2 = np.arange(0,36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [204]:
# Swap columns 0 & 1
m2[:,[0, 1]] = m2[:,[1, 0]]
m2


array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

In [205]:
# swap columns 2 & 3
m2[:,[2, 3]] = m2[:,[3, 2]]
m2

array([[ 1,  0,  3,  2,  4,  5],
       [ 7,  6,  9,  8, 10, 11],
       [13, 12, 15, 14, 16, 17],
       [19, 18, 21, 20, 22, 23],
       [25, 24, 27, 26, 28, 29],
       [31, 30, 33, 32, 34, 35]])

**Concatenate Matrices**

**Matrix Concatenation :**
https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html
(https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)

In [206]:
A = np.array([[1,2] , [3,4] ,[5,6]])
B = np.array([[1,1] , [1,1]])
C = np.concatenate((A,B))
C


array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

**Matrix Addition**

In [207]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
C = M+N
print("\n Matrix Addition (M+N) ==> \n", C)
# OR
C = np.add(M,N,dtype = np.float64)
print("\n Matrix Addition using np.add ==> \n", C)
#********************************************************#



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Addition (M+N) ==> 
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add ==> 
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


**Matrix subtraction**

In [208]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
C = M-N
print("\n Matrix Subtraction (M-N) ==> \n", C)
# OR
C = np.subtract(M,N,dtype = np.float64)
print("\n Matrix Subtraction using np.subtract ==> \n", C)
#********************************************************#



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Subtraction (M-N) ==> 
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix Subtraction using np.subtract ==> 
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


**Matrices Scalar Multiplication**

https://www.youtube.com/watch?v=4lHyTQH1iS8&list=PLmdFyQYShrjcoVkhCCIwxNj9N4rW1-T5I&index=9

In [209]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
C = 10
print("\n Matrix (M) ==> \n", M)
print("\nMatrices Scalar Multiplication ==> \n", C*M)
# OR
print("\nMatrices Scalar Multiplication ==> \n", np.multiply(C,M))



 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Matrices Scalar Multiplication ==> 
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]

Matrices Scalar Multiplication ==> 
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]


**Transpose of a matrix**
https://www.youtube.com/watch?v=g_Rz94DXvNo&list=PLmdFyQYShrjcoVkhCCIwxNj9N4rW1-T5I&index=13


In [210]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nTranspose of M ==> \n", np.transpose(M))
# OR
print("\nTranspose of M ==> \n", M.T)



 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


**Determinant of a matrix**
+ Determinant of a matrix :


+ https://www.youtube.com/watch?v=21LWuY8i6Hw&t=88s
+ https://www.youtube.com/watch?v=Ip3X9LOh2dk&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=6
+ https://www.youtube.com/watch?v=Ip3X9LOh2dk&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=6

In [211]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nDeterminant of M ==> ", np.linalg.det(M))



 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Determinant of M ==>  195.0


**Rank of a matrix**

In [212]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nRank of M ==> ", np.linalg.matrix_rank(M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of M ==>  3


**Trace of matrix**

In [213]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nTrace of M ==> ", np.trace(M))



 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Trace of M ==>  -2


**Inverse of matrix A**

+ Inverse of a matrix 
+ https://www.youtube.com/watch?v=pKZyszzmyeQ

In [214]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nInverse of M ==> \n", np.linalg.inv(M))



 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


**Matrix Multiplication (pointwise
multiplication)** 

In [215]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Point-Wise Multiplication of M & N ==> \n", M*N)
# OR
print("\n Point-Wise Multiplication of M & N ==> \n", np.multiply(M,N))



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Point-Wise Multiplication of M & N ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Point-Wise Multiplication of M & N ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


**Matrix dot product**

+ Matrix Multiplication :


https://www.youtube.com/watch?v=vzt9c7iWPxs&t=207s
https://www.youtube.com/watch?v=XkY2DOUCWMU&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=4
https://www.youtube.com/watch?v=XkY2DOUCWMU&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=4

In [216]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Matrix Dot Product ==> \n", M@N)
# OR
print("\n Matrix Dot Product using np.matmul ==> \n", np.matmul(M,N))
# OR
print("\n Matrix Dot Product using np.dot ==> \n", np.dot(M,N))



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Dot Product ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.matmul ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.dot ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]


**Matrix Division**

In [217]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Matrix Division (M/N) ==> \n", M/N)
# OR
print("\n Matrix Division (M/N) ==> \n", np.divide(M,N))


 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Division (M/N) ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N) ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


**Sum of all elements in a matrix**


In [218]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Sum of all elements in a Matrix ==>")
print (np.sum(N))



 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix ==>
18


**Column-Wise Addition**

In [219]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))



 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


**Row-Wise Addition**

In [220]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Row-Wise summation ==>")
print (np.sum(N,axis=1))



 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation ==>
[3 6 9]


### Kronecker Product of matrices

+ https://www.youtube.com/watch?v=e1UJXvu8VZk

In [221]:
M1 = np.array([[1,2,3] , [4,5,6]]) 
M1


array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
M2 = np.array([[10,10,10],[10,10,10]])
M2


array([[10, 10, 10],
       [10, 10, 10]])

In [223]:
np.kron(M1,M2)


array([[10, 10, 10, 20, 20, 20, 30, 30, 30],
       [10, 10, 10, 20, 20, 20, 30, 30, 30],
       [40, 40, 40, 50, 50, 50, 60, 60, 60],
       [40, 40, 40, 50, 50, 50, 60, 60, 60]])

**Matrix Powers**

In [224]:
M1 = np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [225]:
#Matrix to the power 3
M1@M1@M1


array([[ 57,  78],
       [156, 213]])

In [226]:
#Matrix to the power 3
np.linalg.matrix_power(M1,3)


array([[ 57,  78],
       [156, 213]])

**Tensor**

+ What is tensor
+https://www.youtube.com/watch?v=f5liqUk0ZTw
+https://www.youtube.com/watch?v=bpG3gqDM80w&t=634s
+https://www.youtube.com/watch?v=uaQeXi4E7gA

In [227]:
# Create Tensor
T1 = np.array([
 [[1,2,3], [4,5,6], [7,8,9]],
 [[10,20,30], [40,50,60], [70,80,90]],
 [[100,200,300], [400,500,600], [700,800,900]],
 ])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [228]:
T2 = np.array([
 [[0,0,0] , [0,0,0] , [0,0,0]],
 [[1,1,1] , [1,1,1] , [1,1,1]],
 [[2,2,2] , [2,2,2] , [2,2,2]]
 
])
T2


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

**Tensor Addition**

In [229]:
A = T1+T2
A


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [230]:
np.add(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

**Tensor Subtraction**

In [231]:
S = T1-T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [232]:
np.subtract(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

**Tensor Element-Wise Product**

In [233]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [234]:
np.multiply(T1,T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

**Tensor Element-Wise Division**

In [235]:
D = T1/T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [236]:
np.divide(T1,T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

**Tensor Dot Product**

In [237]:
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [238]:
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [239]:
np.tensordot(T1,T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

**Solving Equations**
+ 𝐴𝑋 = 𝐵

*Solving Equations :*
+ https://www.youtube.com/watch?v=NNmiOoWt86M
+ https://www.youtube.com/watch?v=a2z7sZ4MSqo

In [240]:
A = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
B = np.random.random((3,1))
B


array([[0.44764865],
       [0.43777358],
       [0.62069599]])

In [242]:
# Ist Method
X = np.dot(np.linalg.inv(A) , B)
X

array([[ 6.07797827e+14],
       [-1.21559565e+15],
       [ 6.07797827e+14]])

In [243]:
# 2nd Method
X = np.matmul(np.linalg.inv(A) , B)
X

array([[ 6.07797827e+14],
       [-1.21559565e+15],
       [ 6.07797827e+14]])

In [244]:
# 3rd Method
X = np.linalg.inv(A)@B
X


array([[ 6.07797827e+14],
       [-1.21559565e+15],
       [ 6.07797827e+14]])

In [245]:
# 4th Method
X = np.linalg.solve(A,B)
X

array([[ 6.07797827e+14],
       [-1.21559565e+15],
       [ 6.07797827e+14]])